# Generated by Django 5.1.6 on 2025-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_details',
            name='Room_Number',
            field=models.CharField(max_length=50),
        ),
    ]
